---
lang: de



execute: 
  echo: false
  warning: false
  message: false
  
format: 
  docx:
    toc: true
    toc-title: Inhalt
    reference-doc: custom-reference-doc.docx

knitr: 
  opts_chunk:
    dev: ragg_png
    
params:
  lok: hand
  
title: "Contact sensitization in patients with allergic hand eczema: Patterns of sensitization and suspected allergen sources by eczema location: an analysis of patch test data of the Information Network of Departments of Dermatology (IVDK), 2005-2024"
subtitle: "Localisation: `r unname(readRDS('lokalisationen.rds')[params$lok])`"
---

```{r load-libs}
library(gdata) # Um trim() nutzen zu können
library(haven)
library(janitor)
library(kableExtra)
library(knitr)
library(scales) # Um wrap_format() nutzen zu können
library(tidyverse) 
library(quarto)
```

```{r def-paths}
lok <- params$lok
laufw <- "T"
pfad_daten <- str_c(laufw, ":/besondere_auswertungen/handekzem/data")
```

```{r def-misc}
# Dezimalzeichen: Komma
options(OutDec = ",")

# Levels definieren
levels_fragen <- c("Ja", "Nein", "Unbekannt", "Angabe fehlt")
```

```{r data-imp}
moahlfa <- read_sas(data_file = file.path(pfad_daten, str_c("moahlfa_ci2_", lok, ".sas7bdat")))
kontaktstoffe <- read_sas(data_file = file.path(pfad_daten, str_c("kosto_ci2_", lok, ".sas7bdat")))
kofaktoren <- read_sas(data_file = file.path(pfad_daten, str_c("kofak_ci2_", lok, ".sas7bdat")))
kofaktoren_liste <- read_sas(data_file = file.path(pfad_daten, str_c("kofakt_ci2_", lok, ".sas7bdat")))
diagnose <- read_sas(data_file = file.path(pfad_daten, str_c("diag_ci2_", lok, ".sas7bdat")))
hitliste_standardreihe <- read_sas(data_file = file.path(pfad_daten, str_c("listeg_konz_block1_0524_", lok, ".sas7bdat")))
```

# MOAHLFA-Index

```{r moahlfa-tbl}
moahlfa |> 
mutate(Merkmal = merkmal,
       Index = index,
       Anzahl = count_pos,
       `% Positiv [95%-KI]` = str_c(
          round(percent_pos,
                 digits = 1), 
          " [", 
          str_replace_all(
            str_c(
              trim(
                format(round(lclpos3, digits = 1),
                       nsmall = 1)
                ),
              "-", 
              trim(
                format(round(uclpos3, digits = 1),
                       nsmall = 1))
              ),
            "\\.", 
            ","),
          "]"),
       .keep = "none"
) |> 
  knitr::kable(caption = str_c("MOAHLFA-Index, Lokalisation: ",
      unname(readRDS('lokalisationen.rds')[params$lok]), 
      "."))
```

\newpage

# Kontaktstoffe

```{r kontaktstoffe-tbl}
kontaktstoffe |> 
  mutate(Bezeichnung = kontsto,
         #Fälle = trials_pos,
         Anzahl = count_pos,
         `% Positiv [95%-KI]` = str_c(
          round(percent_pos,
                 digits = 1), 
          " [", 
          str_replace_all(
            str_c(
              trim(
                format(round(lclpos3, digits = 1),
                       nsmall = 1)
                ),
              "-", 
              trim(
                format(round(uclpos3, digits = 1),
                       nsmall = 1))
              ),
            "\\.", 
            ","),
          "]"),
       .keep = "none") |> 
  knitr::kable(caption = str_c("Kontaktstoffe, Lokalisation: ",
      unname(readRDS('lokalisationen.rds')[params$lok]), 
      ", N=", 
      unique(kontaktstoffe$trials_pos),
      "."))
```

\newpage

# Hauptdiagnose

```{r diagnose-tbl}
diagnose |> 
  mutate(Bezeichnung = diagbez,
         #Fälle = trials_pos,
         Anzahl = count_pos,
         `% Positiv [95%-KI]` = str_c(
          round(percent_pos,
                 digits = 1), 
          " [", 
          str_replace_all(
            str_c(
              trim(
                format(round(lclpos3, digits = 1),
                       nsmall = 1)
                ),
              "-", 
              trim(
                format(round(uclpos3, digits = 1),
                       nsmall = 1))
              ),
            "\\.", 
            ","),
          "]"),
       .keep = "none") |> 
  knitr::kable(caption = str_c("Hauptdiagnose, Lokalisation: ",
                               unname(readRDS('lokalisationen.rds')[params$lok]), 
                               ", N=", 
                               unique(diagnose$trials_pos),
                               "."))
```

\newpage

# Bestehen zusätzliche Kofaktoren?

```{r kofaktoren-tbl}
kofaktoren |> 
  mutate(KOFA = ifelse(KOFA == "unbekannt", "Unbekannt", KOFA),
         Angabe = fct_relevel(KOFA,
                              levels_fragen),
         #Fälle = trials_pos,
         Anzahl = count_pos,
         `% Positiv [95%-KI]` = str_c(
          round(percent_pos,
                 digits = 1), 
          " [", 
          str_replace_all(
            str_c(
              trim(
                format(round(lclpos3, digits = 1),
                       nsmall = 1)
                ),
              "-", 
              trim(
                format(round(uclpos3, digits = 1),
                       nsmall = 1))
              ),
            "\\.", 
            ","),
          "]"),
       .keep = "none") |> 
  select(- KOFA) |> 
  arrange(Angabe) |> 
  knitr::kable(caption = str_c("Kofaktoren, Lokalisation: ",
                               unname(readRDS('lokalisationen.rds')[params$lok]), 
                               ", N=", 
                               unique(kofaktoren$trials_pos[1]),
                               "."))
```

\newpage

# Zusätzlich bestehende Kofaktoren

```{r kofakt2-tbl}
kofaktoren_liste |> 
  mutate(Bezeichnung = kofak,
         #Fälle = trials_pos,
         Anzahl = count_pos,
         `% Positiv [95%-KI]` = str_c(
          round(percent_pos,
                 digits = 1), 
          " [", 
          str_replace_all(
            str_c(
              trim(
                format(round(lclpos3, digits = 1),
                       nsmall = 1)
                ),
              "-", 
              trim(
                format(round(uclpos3, digits = 1),
                       nsmall = 1))
              ),
            "\\.", 
            ","),
          "]"),
       .keep = "none") |> 
  knitr::kable(caption = str_c("Zusätzlich bestehende Kofaktoren, Lokalisation: ",
                               unname(readRDS('lokalisationen.rds')[params$lok]), 
                               ", N=", 
                               unique(kofaktoren_liste$trials_pos[1]),
                               "."))
```

\newpage

# Epikutantestung Standardreihe (`r unname(readRDS('lokalisationen.rds')[params$lok])`)

```{r hitliste_standardreihe-tbl}
# Welche KI-Grenzen soll ich hier nehmen? Unklar. Viele Vars im Dataset.

hitliste_standardreihe |> 
    mutate(Bezeichnung = substanz,
         #Fälle = testzahl,
         `Konz.` = round_half_up(konz, digits = 1),
         Anzahl = count,
         `% Positiv [95%-KI]` = str_c(
          format(round_half_up(percent2, digits = 1),
                 nsmall = 1), 
          " [", 
          str_replace_all(
            str_c(
              trim(
                format(round_half_up(lcl, digits = 1),
                       nsmall = 1)
                ),
              "-", 
              trim(
                format(round_half_up(ucl, digits = 1),
                       nsmall = 1))
              ),
            "\\.", 
            ","),
          "]"),
         .keep = "used"
         ) |> 
  select(7:10) |> 
  arrange(desc(`% Positiv [95%-KI]`)) |> 
  knitr::kable(caption = str_c("Epikutantestung Standardreihe, Lokalisation: ",
      unname(readRDS('lokalisationen.rds')[params$lok]), 
      "."))
```